### ISSUE TITLE
Docker fails to run

### ISSUE THREAD

**Issue by raviram203** [HSBawa/icp-ce-on-linux-containers#1]
ICP installation failed as docker failed to run on dev-boot. I tried `docker run hello-world` on `testimage`. It fails with errors (please see attached file). Ran into the same problem with zfs and, later, with btrfs. Host machine is Ubuntu 17.10. Any ideas? Will plug away as time permits. 
[icp-docker-error.txt](https://github.com/HSBawa/icp-ce-on-linux-containers/files/1777814/icp-docker-error.txt)

**Comment by HSBawa** [comment]
1) The 'testimage' issue that you are seeing is because of the missing privileges (command line or part of profile) that would allow LXD to run Docker. Running Docker in LXD is running container in container. 

2) For ICP installation fail: Can you share the 'journalctl' logs for the docker service on dev-boot node?

**Comment by raviram203** [comment]
Sorry. I destroyed the lxc containers. I use `snap install lxd`, as the `apt` does not have the latest release for `lxd`. I had also moved the lxd folder from the boot device to a hard drive and created a link. Thought the link might be the problem. Removed `lxd`, reinstalled from `snap`, did not move/link lxd folder, took defaults for `lxd init` and created the xenial. Same problem with testimage and `docker run hello-world`. Will try once more with `apt install lxd`.

**Comment by HSBawa** [comment]
Hi Ravi,

Seems like  LXD is not configured correctly on your computer. Following is some  helpful information/steps:
- Install latest Linux Container (LXD) on Ubuntu 16.04/17.10 (change 'xenial' to 'artful' for 17.10):
   - `sudo apt install -t xenial-backports lxd lxd-client` 
   - Note: To run Docker inside LXD, additional configuration is part of Packer and Terraform code.
- Initialize LXD 
  - Run 'sudo lxd init' 
    - Select 'btrfs' driver 
    - Provide minimum of 40 GB storage
    - Name storage as 'default'
    - Continue to create network bridge (lxdbr0) with ipv4 (none for ipv6), if you are running init for first time. 
       - Must allow internet access. 
  - Run 'lxc profile|network|storage  list' commands to check/validate profile, network or storage created. Use lxc help for additional commands.
  - Running init for 1st time will also create 'default' profile. 
- Create LXD Cluster and Install ICP
  - Once LXD is initialized correctly(pre-requisite), follow documentation [Step 1](https://github.com/HSBawa/icp-ce-on-linux-containers/wiki/1.0-Create-Base-Linux-Container-Image-For-IBM-Cloud-Private-with-Hashicorp-Packer) and [Step 2](https://github.com/HSBawa/icp-ce-on-linux-containers/wiki/2.0-Create-LXD-Cluster-and-ICP-install-with-Terraform).

Hope this helps.

**Comment by raviram203** [comment]
Thanks, Hari. I agree. The problem is with LXC/D, not scripts in the repo. Pretty sure I did everything in your note, except include `xenial-backports` or use `sudo` for `lxd init`. The lxc container has internet access and is able to download files. I run into the same error trying to run `hello-world` regardless of `lxd` from `apt` or `snap`. Same problem whether I build the lxc with the repo script or install docker manually. Thanks for advice. I will close this issue.

**Comment by HSBawa** [comment]
Hi Ravi, 

Following is Docker on LXD example (as console screenshot): 
- [Docker hello-world on LXD ](https://github.com/HSBawa/icp-ce-on-linux-containers/blob/master/docs/screenshots/docker-on-lxd-example.png)

Let me know if you still encounter any issues running Docker on Linux Container.

**Comment by raviram203** [comment]
`lxc launch ubuntu:16.04 testimage-for-docker -c security.nesting=true` runs docker hello-world. Thanks for posting the update. The ICP build still fails. Have attached the console logs, journalctl from docker.service, hosts and config.yaml (only active lines). 

I created lxcshare folder in my home directory. Hope the owner:group settings are correct. 
`drwxrwxr-x  2 ravi lxd  4096 Mar  6 16:47 lxcshare/`

Will plug away. Does anything obvious jump out?
[2018-03-06-a-icp-console-log.txt](https://github.com/HSBawa/icp-ce-on-linux-containers/files/1787382/2018-03-06-a-icp-console-log.txt)

[2018-03-06-a-icp-jctl-docker-log.txt](https://github.com/HSBawa/icp-ce-on-linux-containers/files/1787383/2018-03-06-a-icp-jctl-docker-log.txt)

**Comment by HSBawa** [comment]
From logs:
- Custom LXD image was created successfully. **(Success)**
- Boot and Master nodes are up and running with Docker **(Success)**
- Proxy, Management and Worker(1,2,3) nodes are not getting started. For this reason host configuration fails which in turn breaks ICP install. **(Fail)**

Next steps recommended:
- Node start time may vary from environment to environment based on configuration. Change 'sleep 20' to a higher number in [init_boot.sh](https://github.com/HSBawa/icp-ce-on-linux-containers/blob/master/utils/init_boot.sh) (line 7) until nodes are up and running
- If above does not work, check for your LXD nodes for any other issues.

**Comment by raviram203** [comment]
Thanks, Hari. Yes, ICP ce is running. I need to expand storage. I had given a measly 50GB for btrfs volume with `lxd init`. 42GB is allocated with zero available. If you have tips to expand storage, please let me know. Will close this issue, again. I should have opened a new issue for ICP installation failure. I forgot this issue's title was "Docker failed".

**Comment by HSBawa** [comment]
Hi Ravi,

Glad to hear ICP-CE is up and running for you.  I have not tried expanding storage as I have assigned plenty of GB's in advance. 

Just a thought: Now that you have IaC working, so I guess now is the good time to tune LXD to your needs and re-install ICP again.
