### ISSUE TITLE
LXD/LXC Start Over

### ISSUE THREAD

**Issue by raviram203** [HSBawa/icp-ce-on-linux-containers#14]
Not really a problem with your code, Hari. I wanted to clean house and migrate to LXD snap. I deleted containers & images before I migrated LXD from apt to snap (your instructions helped). I saw four LXC networks but only one seemed to exist. I wanted to delete all, but was able to delete only `lxdbr0` (the only network which seemed to exist). Any tips on removing networks? 
```
ravi@toga:~/git/icp-ce-on-linux-containers$ lxc network list
+---------+----------+---------+-------------+---------+
|  NAME   |   TYPE   | MANAGED | DESCRIPTION | USED BY |
+---------+----------+---------+-------------+---------+
| docker0 | bridge   | NO      |             | 0       |
+---------+----------+---------+-------------+---------+
| enp31s0 | physical | NO      |             | 0       |
+---------+----------+---------+-------------+---------+
| lxcbr0  | bridge   | NO      |             | 0       |
+---------+----------+---------+-------------+---------+
| lxdbr0  | bridge   | YES     |             | 0       |
+---------+----------+---------+-------------+---------+
```
But three do not seem to exist. Is this a problem?
```
ravi@toga:~/git/icp-ce-on-linux-containers$ lxc network info lxcbr0
Error: Interface 'lxcbr0' not found
ravi@toga:~/git/icp-ce-on-linux-containers$ lxc network info docker0 
Error: Interface 'docker0' not found
ravi@toga:~/git/icp-ce-on-linux-containers$ lxc network info enp31s0 
Error: Interface 'enp31s0' not found
```
Only one network seems to exist:
```
ravi@toga:~/git/icp-ce-on-linux-containers$ lxc network info lxdbr0 
Name: lxdbr0
MAC address: ba:b7:05:96:f5:89
MTU: 1500
State: up

Ips:
  inet	10.31.221.1
  inet6	fd42:8d02:8f0f:9205::1
  inet6	fe80::b8b7:5ff:fe96:f589

Network usage:
  Bytes received: 0B
  Bytes sent: 35.55kB
  Packets received: 0
  Packets sent: 208
```
Managed to delete `lxdbr0`, but not the other three `Error: not found`.
```
ravi@toga:~/git/icp-ce-on-linux-containers$ lxc network delete lxdbr0 
Network lxdbr0 deleted
```

**Comment by HSBawa** [comment]
HI @raviram203, I haven't encountered this issue, so may not be able to help much. I would suggest Linux Containers Forum for best response.

If planning to start from scratch, I would uninstall lxd (snap) and re-install and init it again. I would also make sure to remove APT version of lLXD (w/ purge option).

**Comment by raviram203** [comment]
Will do. Will purge snap LXD. I purged apt LXD earlier.
