### ISSUE TITLE
Small error in `icp-login-3.1.0-ce.sh`

### ISSUE THREAD

**Issue by raviram203** [HSBawa/icp-ce-on-linux-containers#16]
Nice to have the login script. I tweaked it just a little. Removed `devicpcluster`. This works (note: no cluster name). Well, it does not throw an error. But there is very little in the output.
```
$ cloudctl pm password-rules default
Name   Description   Regex 
```

Throws error.
```
$ cloudctl pm password-rules devicpcluster default
FAILED
Incorrect Usage.

NAME:
   password-rules - List the password rules for a namespace.

USAGE:
   cloudctl pm password-rules <namespace>

PARAMETERS:
   -s      Do not show the column headers in the output.
   --json  Display output in JSON format.
```

**Comment by HSBawa** [comment]
@raviram203  Commented it out. :-) Always slips out of my action items ... will fix it in next version.
