### ISSUE TITLE
[Q] This is more of a question

### ISSUE THREAD

**Issue by DarkBlaez** [HSBawa/icp-ce-on-linux-containers#18]
I have a questions but will also report this minor bug. When I pass the --force option to create-cluster.sh it will throw an error reporting an extra '-' so something like '- --force'  and error out.

My real question is I have spun up the cluster as-is but with 780G storage pool and each worker having 100G , 4 workers.

I noticed that in the Dashboard ICP shows 80G shared. How does all this relate to the overall storage utilized or taken from the pool? 

I suppose my end result would be to be able to utilize the full 780G as best as possible and that perhaps each worker should only have 20G-40G and reduce the storage pool size, leaving the rest of the storage to perhaps mount as NFS on the host and inject in to ICP.

Thoughts? Again I think my best approach is workers to run loads and use PV allocations for storage which I think is the norm and thus perhaps I should not be allocating 100G to each worker.

Hari can you provide me some clarification and thoughts around this> Thanks so much

DB-

**Comment by HSBawa** [comment]
Hi. @DarkBlaez , 80Gi that you are seeing is from the PVs space  (and not disk size) that got allocated during ICP install. You can view PV details at `https://<console_ip>:8443/console/platform/storage`.  Once more PV are created, additional storage will show on Dashboard. 

Regarding 100Gi for worker node: 
You can view disk utilization by running command `df -kH` on host machine. In screenshot below, you will see with, default install, worker node disk utilization is @ 27%-29%.  100Gi is definitely a lot. Based on your requirements/usage, please adjust your node disk space accordingly.  IBM ICP Knowledge Center has documented recommended specifications that you can also refer to. 

![Example df -kH command result](https://user-images.githubusercontent.com/19266024/54168591-a9942000-4445-11e9-84ba-3b0af8f73f55.png)

On NFS Server, I would definitely recommend using it. If there is no available NFS Server, users can actually configure their host as NFS server. To avoid changes to host, optionally, users can also create NFS Server on a LXD container and sharing host folder. There should be a link to NFS Server on Container at the bottom of instructions on main page.

Hope this helps.

**Comment by HSBawa** [comment]
@DarkBlaez I will also take a look into the parameter issue. Thanks for sharing.
