### ISSUE TITLE
Error: cannot connect to Tiller

### ISSUE THREAD

**Issue by raviram203** [HSBawa/icp-ce-on-linux-containers#19]
I logged into ICP using `icp-login-3.1.2-ce.sh`. Thought I should see `tiller`
```
ravi@toga:~/git/icp-ce-on-linux-containers$ helm init --client-only
$HELM_HOME has been configured at /home/ravi/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
ravi@toga:~/git/icp-ce-on-linux-containers$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Error: cannot connect to Tiller
```
Response to `kubectl get deployments --all-namespaces` contains the line:
```
NAMESPACE      NAME                                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system    tiller-deploy                                 1         1         1            1           4h12m
```
Or should I use `helm init` rather than `helm init --client-only` ?

**Comment by HSBawa** [comment]
Please try with `helm version --tls` 
`helm init --client-only` is correct way to initialize. 
Here is quick reference on [IBM Helm CLI setup](https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.2/app_center/create_helm_cli.html).

**Comment by raviram203** [comment]
You are correct. I had `--notls` in my head and bumped into the wall. Thanks, again.

FYI... I had one successful ICP build with snap LXD 3.11. And then a few failures. Wiped snap LXD and switched to apt LXD 3.0.3. Had a few failures and then a successful build. All failures (on the surface) looked alike -- `master` LXC is stopped and installer just keeps trying.
