### ISSUE TITLE
[Q] Routing Metal LB

### ISSUE THREAD

**Issue by DarkBlaez** [HSBawa/icp-ce-on-linux-containers#20]
Just a question, I see HAProxy is installed and assuming for routing from PODS to the host for access externally via the host IP. My question is, if I which to use Metal LB to expose services via LoadBalancer the IP range for Layer2 should come from the same subnet that my Hosts are being assigned. So as an example:

My Host for this is 10.10.100.X and the range for the LXC is at 10.50.50.X . Since I would like to consider Metal LB for exposing PODS I would want my LXC containers to be in the same range as host so 10.10.100.X  I have tried this but looks like when doing so the containers cannot resolve the external registries to pull the containers.

Is there anything else I should consider ? I did test Metal LB with the existing 10.50.50.x assignment and did see my PODs when exposed via LoadBalancer were able to be accessed but only from the Host not external do such. Ideally I would like to use Metal LB to be able to access any svc I explose as a unique IP in the range as described above. Just looking for thoughts or why possibly when the range of the LXC containers is within the same subnet as host that it is unable to see or resolve the external registries to pull images

Thanks
DB

**Comment by HSBawa** [comment]
@DarkBlaez You can have LXD containers use the same CIDR range as host by using nictype as macvlan. But for this script, for now, only option is to create a new bridge with given CIDR and containers tie to that network. This being said, script will require some decent tweaks to incorporate macvlan as an option.I was thinking of adding that option, but may take some time. 

I am able to expose services, outside of host  via `ingress`. I will check/validate it again.
