### ISSUE TITLE
Kubernetes in icp_master did not start properly

### ISSUE THREAD

**Issue by anhquan22** [HSBawa/icp-ce-on-linux-containers#23]
I setup ICP cluster in Google cloud platform. (8CPU, 30GB Ram, 500GB Disk)
Run the command ./create_cluster.sh -es=demo
When finished, i get some error blow.
How do I start Kubernetes properly? Thanks
![image_2019_6_13](https://user-images.githubusercontent.com/740573/59481779-e7af3e80-8e8f-11e9-8bab-46b34c0d2569.png)

**Comment by HSBawa** [comment]
I have not tried on Google Cloud but I believe I have seen this Issue with LXD terraform where it gets stuck at master node. 

What i did was, destroyed cluster and started process again and it worked.

sudo ./destroy-cluster.sh
sudo ./terra-clean.sh
sudo ./create-cluster.sh


Let me know how it goes.

**Comment by anhquan22** [comment]
> 
> 
> I have not tried on Google Cloud but I believe I have seen this Issue with LXD terraform where it gets stuck at master node.
> 
> What i did was, destroyed cluster and started process again and it worked.
> 
> sudo ./destroy-cluster.sh
> sudo ./terra-clean.sh
> sudo ./create-cluster.sh
> 
> Let me know how it goes.

Thank HSBawa, i will try do this recipes.

**Comment by anhquan22** [comment]
I tried to follow your instructions but fail.
This is google cloud platform, I created.
![screencapture-console-cloud-google-compute-instancesDetail-zones-us-central1-a-instances-ibm-test-2019-06-17-14_23_00](https://user-images.githubusercontent.com/740573/59596335-b51c7480-9121-11e9-8039-ea8376f8c8ce.jpg)

Putty log:
[putty.log](https://github.com/HSBawa/icp-ce-on-linux-containers/files/3296293/putty.log)

Thank for your support.

**Comment by HSBawa** [comment]
Looking at the logs, seems like issue is different what I assumed earlier. **Kubernetes failing to start**   
I have not tested with Google Cloud VM. I will try it out when I have opportunity sometime this or next week. 

Following is one option you can try: 
In **install.properties**,  can find and update following (assuming 35.222.xxx.xxx is your external IP address): 
**ICP_AUTO_LOOKUP_HOST_IP_ADDRESS_AS_LB_ADDRESS**=n
**ICP_MASTER_LB_ADDRESS**=35.222.xxx.xxx
**ICP_PROXY_LB_ADDRESS**=35.222.xxx.xxx

**Comment by anhquan22** [comment]
> 
> 
> Looking at the logs, seems like issue is different from what I assumed earlier. **Kubernetes failing to start**
> I have not tested with Google Cloud VM. I will try it out when I have opportunity sometime this or next week.
> 
> Following is one option you can try:
> In **install.properties**, can find and update following (assuming 35.222.xxx.xxx is your external IP address):
> **ICP_AUTO_LOOKUP_HOST_IP_ADDRESS_AS_LB_ADDRESS**=n
> **ICP_MASTER_LB_ADDRESS**=35.222.xxx.xxx
> **ICP_PROXY_LB_ADDRESS**=35.222.xxx.xxx
I changed the contents of the **install.properties** but failed. Thank you for your help. I will try to handle this error.
