### ISSUE TITLE
Not able to destroy terraform network & profile modules

### ISSUE THREAD

**Issue by raviram203** [HSBawa/icp-ce-on-linux-containers#5]
hi, Hari.
Don't think this issue is a problem in your code, but I have not been able to solve this riddle despite several hours of effort and repeated runs of `terra-clean.sh` and `terraform destroy`. I am using the latest version of the code. `install-w-terra.sh` or manual invocations of the commands produces the same errors. Did I miss the obvious? 
Thanks, Ravi
```
Error: Error applying plan:

2 error(s) occurred:

* module.network.lxd_network.icp_ce_network: 1 error(s) occurred:

* lxd_network.icp_ce_network: The network already exists
* module.profile.lxd_profile.icp_ce: 1 error(s) occurred:

* lxd_profile.icp_ce: The profile already exists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by HSBawa** [comment]
Hi Ravi, Try running following scripts in order:

1. [destroy-cluster-manual.sh](https://github.com/HSBawa/icp-ce-on-linux-containers/blob/master/destroy-cluster-manual.sh) ex: destroy-cluster-manual.sh dev . This will remove elements of previous cluster for which terraform state is not current. 
2. terra-clean.sh (deletes current terraform state)
3. install-w-terra.sh (start fresh)

Hope this helps.
