### ISSUE TITLE
GlusterFS Server IP Address

### ISSUE THREAD

**Issue by raviram203** [HSBawa/icp-ce-on-linux-containers#7]
hi, Hari
Am running through another series of experiments. The GlusterFS servers and ICP are running. I am able to ping the glusterfs servers from the ICP worker nodes. All good. I wondered how the glusterfs server IP addresses became `10.31.221.117` and `10.31.221.132`. I expected them to inherit values from `glusterfs-server-lxc.sh`:
```
node_ip_pre=10.71.17.
start_ip=190
``` 
I wanted to understand the logic. Would appreciate guidance.
Thanks, Ravi

**Comment by HSBawa** [comment]
Hi @raviram203 

It seems like the lxd bridge on your machine uses sub-net of 10.31.221.x, where as the shell script variable is initialized to 10.71.17.x.

There are 2 options:
a) change node_ip_pre value to 10.31.221.
b) update existing, or create a new lxd bridge to use the sub-net of 10.71.17.x.

Hope this helps.

**Comment by raviram203** [comment]
Yes, indeed. An eye opener. Looks like the lxdbr0 takes precedence. Which seems appropriate. Do you have links which would explain? Thanks.
```
$ lxc network show lxdbr0 
config:
  ipv4.address: 10.31.221.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:8d02:8f0f:9205::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/glusterfs-server-1
- /1.0/containers/glusterfs-server-2
managed: true
status: Created
locations:
- none
```
