### ISSUE TITLE
Unable to create client for remote [local-https]

### ISSUE THREAD

**Issue by raviram203** [HSBawa/icp-ce-on-linux-containers#9]
Vanilla trial run -- changed `source = "/media/lxcshare"` in `main.tf` and ran through commands of Option 2 in [2.0 Create LXD Cluster and ICP install with Terraform · HSBawa/icp-ce-on-linux-containers Wiki](https://github.com/HSBawa/icp-ce-on-linux-containers/wiki/2.0-Create-LXD-Cluster-and-ICP-install-with-Terraform). 
Ubuntu 18.04 host, image: `xenial-container-for-icp-lvm-bionic-host`, Snap 3.01 installed via APT. After I saw the error, I installed Apache. Now `http://127.0.0.1` works, but `https://127.0.0.1:9443` fails. Ran through Option 2 from the top and still the same error. Suggestions?
```
2 error(s) occurred:

* module.network.lxd_network.icp_ce_network: 1 error(s) occurred:

* lxd_network.icp_ce_network: Unable to create client for remote [local-https]: Could not get remote certificate: Get https://127.0.0.1:9443: Unable to connect to: 127.0.0.1:9443
* module.profile-master-worker.lxd_profile.icp_ce: 1 error(s) occurred:

* lxd_profile.icp_ce: Unable to create client for remote [local-https]: Could not get remote certificate: Get https://127.0.0.1:9443: Unable to connect to: 127.0.0.1:9443
```

**Comment by HSBawa** [comment]
If not done recently, please do a git pull as I have updated code. 

I am guessing there is PORT conflict between Apache and LXD. Can you please verify?
`lxc config get core.https_address`   (assuming it will return [::]:9443)
`https://localhost:9443/`  (must not return Apache web site page but LXD API json response)

If you are using LXD 3.0.1, then you can use Unix Socket and not https :  
* terraform.tfvars - Add  `remote="local"` in lxd  map(see screenshot below). This will make sure that lxd will use unix socket and not network for communication.
![image](https://user-images.githubusercontent.com/19266024/46843434-bcc09800-cda0-11e8-8f7c-f4bcff4bf85a.png)

Let know how it goes.

**Comment by raviram203** [comment]
As always, thank you for the reply. Yes, I synced my fork today, just before I tried the vanilla build. `lxc config get core.https_address` came back empty. `https://localhost:9443/` returns "cannot connect". I inserted `remote="local"` into `terraform.tfars`. Now I get a different error: `lxd_profile.icp_ce_worker.1: The "icp" storage pool doesn't exist.` Searched a bit -- think you have standardized monikers. Will dig deeper. For now, sleep beckons me in PT (even more so you in ET).

**Comment by HSBawa** [comment]
My bad, I think during some testing, I must have changed storage pool from default to icp. I reverted it back to default. Once you do a pull, it should be working. 

I would assume that lxd pool name (storage) on your device  is 'default'. You can verify with `lxc storage list`

terraform.tfvars 
![image](https://user-images.githubusercontent.com/19266024/46848252-cd7c0880-cdb6-11e8-8fea-afb2ce1f3234.png)

**Comment by HSBawa** [comment]
@raviram203 I have also updated code with workaround on the terraform lxd plugin issue with default socket  path when using snap install. 

Now remote="local" should work without issue for both snap or apt based installs (<= v3.0.x  and >= 3.1.x ) and not require network (https) communication.

Hope this change along with updated terraform.tfvars with pool name change will resolve your issue.

**Comment by raviram203** [comment]
Good point about `storage_device_pool`. My LXC `default` profile uses `btrfs-pool1`. Wonder if the problems I encounter are due to the old LXD setup which I used for ICP 2.1. I did not use any preseed yaml file. Please let me know where I could look to solve this puzzle. I set `core.https_address` and `core.trust_password` manually as in a preseed -- did not help.

Synced repo this morning. Created new branch and tweaked `lxcshare` and `storage_device_pool` settings. Ran into errors -- I use LXD from APT, but error message shows it is looking in `/var/snap`:
```

variables.tf
--------------
image="xenial-container-for-icp-lvm-bionic-host"
remote="local"
##remote="local-https"
-------------------------
Error: Error applying plan:

2 error(s) occurred:

* module.profile-master-worker.lxd_profile.icp_ce: 1 error(s) occurred:

* lxd_profile.icp_ce: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory
* module.network.lxd_network.icp_ce_network: 1 error(s) occurred:

* lxd_network.icp_ce_network: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory
=========================================
```
Tweaked variables.tf -- flipped value for `remote`. Ran into the old errors.
```
variables.tf
--------------
image="xenial-container-for-icp-lvm-bionic-host"
remote="local"
##remote="local-https"
-------------------------
Error: Error applying plan:

2 error(s) occurred:

* module.network.lxd_network.icp_ce_network: 1 error(s) occurred:

* lxd_network.icp_ce_network: Unable to create client for remote [local-https]: Could not get remote certificate: Get https://127.0.0.1:10443: Unable to connect to: 127.0.0.1:10443
* module.profile-master-worker.lxd_profile.icp_ce: 1 error(s) occurred:

* lxd_profile.icp_ce: Unable to create client for remote [local-https]: Could not get remote certificate: Get https://127.0.0.1:10443: Unable to connect to: 127.0.0.1:10443
=========================================
```

**Comment by HSBawa** [comment]
@raviram203 can you share remote (local) block from `main.tf` file. Also can you share the `lxd version` results?

**Comment by raviram203** [comment]
Sorry for the trouble. I thought I could play detective from the apply log, but ....

$ which lxd
/usr/bin/lxd

~$ lxd version
3.0.1

[main.tf.zip](https://github.com/HSBawa/icp-ce-on-linux-containers/files/2477268/main.tf.zip)

**Comment by HSBawa** [comment]
@raviram203 From main.tf, seems like unix socket address is set to one for snap (programmatically) lxd is not in snap folder. I tested this logic and worked for me well. But I am guessing my logic may still be buggy, so just in case, can you  share location of your lxc (which lxc) " ?  

   lxd_remote {
      name     = "local"
      scheme   = "unix"
      address  = "/var/snap/lxd/common/lxd/unix.socket"
      password = ""
    }

**Comment by raviram203** [comment]
Tweaked `address` to the APT `unix.socket`. Sorry, I should have grepped `snap` and seen your comment in `main.tf`. After that, I had delete network `devbr0` and profiles `dev-common`. Build is running. Afraid I had enabled terraform DEBUG. So, the ICP build will be super slow. Will keep you posted.

**Comment by raviram203** [comment]
Started from scratch. Synced repo. Same results are before. `icp-login-3.1.0-ce.sh` fails. Not able to download `kubectl` from `dev-mater-0` -- `curl` cannot connect to `10.50.50.101 port 8443` or other ports. I went into the master node with `lxc exec`. Can ping `google.com` and both worker nodes. However, when I tried to `ssh` into worker nodes, they were not in the `known_hosts`. Looks like the key exchange between nodes did not happen -- is this a problem? Used to be a big deal in v2.1. Have been away from ICP for several months. Will keep hunting. If I missed something obvious, please let me know.

**Comment by HSBawa** [comment]
Can you share screenshot where ICP install hangs? Also if it is in non-debug mode that show what tasks fails. I am guessing this issue is related to some settings.

If installation is not complete, login scripts will work as server is not up. The icp login script uploaded in git are example scripts generated from test installs and will be overwritten with new install, based in configuration, and is for convenience. 

kubectl and helm can be downloaded from their respective sites too,

**Comment by raviram203** [comment]
I found something, almost at the end of the debug log. Does it ring a bell? Will dive deeper in a couple of hours.
[icp-install-error.txt](https://github.com/HSBawa/icp-ce-on-linux-containers/files/2494078/icp-install-error.txt)

**Comment by HSBawa** [comment]
Are you using BTRFS or LVM? I am guessing your proxy  API issue and not started.

**Comment by raviram203** [comment]
Afraid that might be the problem. I am using `xenial-packer-lxd-image-lvm-for-bionic-host` along with lxcshare (btrfs), "default" storage is `btrfs-pool1`. The plan was to create more btrfs storage pools... All images, containers and profiles are in `btrfs-pool1` with plenty of free space. See below. Not sure what type of storage the container uses for `/` . Please let me know if you see the problem or cure.

The goal was to make sure I could create a vanilla build using the same LXD infrastructure as before, before integrating gluster & ceph. Storage management is IMHO the achille's heel of containers.
```
$ lxc profile show dev-master-0 
config: {}
description: LXD Profile for dev-master-0
devices:
  eth0:
    ipv4.address: 10.50.50.101
    nictype: bridged
    parent: devbr0
    type: nic
  root:
    path: /
    pool: btrfs-pool1
    size: 30GB
    type: disk
name: dev-master-0
used_by:
- /1.0/containers/dev-master-0
```

**Comment by HSBawa** [comment]
**Pool**

 * pool: btrfs-pool1 . btrfs-pool1 is your lxd storage name. 
 * If you have all storage of type BTRFS, you will have to create one with type LVM and provide that name as pool. 
 * See link to article on [ LXD storage](https://blog.ubuntu.com/2017/07/12/storage-management-in-lxd-2-15) that may be of help to you in managing storage. Make sure thin provisioning tools are installed before. (sudo apt-get install -y thin-provisioning-tools) 
* Make sure to use LVM enabled image for your nodes (packer file names with lvm mid/postfix)  
---------------------------------

**10.50.50.101:8001**
 * Port 8001 is used by Kube API Server. 
 * Kube API Server services REST operations and provides the frontend to the cluster’s shared state through which all other components interact. 
 * Port 8001 must be available on Master Node only. 

Hope this helps.

**Comment by HSBawa** [comment]
**Pool**

 * pool: btrfs-pool1
    * btrfs-pool1 is your lxd storage name and I guess, is of type is `btrfs`
 * If that's the only storage you have, then you will have to create one of type `lvm`.
 * See link to article on [ LXD storage](https://blog.ubuntu.com/2017/07/12/storage-management-in-lxd-2-15). _Thin provisioning tools_ need to be installed before you create storage of type `lvm`. 
   * `sudo apt-get install -y thin-provisioning-tools`
* Use `lvm` enabled image for your nodes. Packer file with `lvm` as mid/postfix can be used, depending upon platform.   
---------------------------------

**10.50.50.101:8001**
 * Port 8001 is used by Kube API Server. 
 * Kube API Server services REST operations and provides the frontend to the cluster’s shared state through which all other components interact. 
 * Port 8001 must be available on Master Node only. 

Hope this helps.

**Comment by raviram203** [comment]
Will do. Thanks for the advice. Tried to wing it. Failed to takeoff. Dived into mud hole.

**Comment by HSBawa** [comment]
@raviram203 I know it is confusing. I think btrfs works very well. But what we dealing here is Docker and it has some of it constraints. Post ICP 2.1.0.2, I had no success with btrfs and zfs. Probably was mix of Docker and Kube.  

For once, I was stuck at same error, as you are now, for long long time. 

See Docker link on [storage drivers](https://docs.docker.com/storage/storagedriver/select-storage-driver/)
See following chart on Docker storage driver and matching backing file system [overlay2 + lvm (ext4)]:
![image](https://user-images.githubusercontent.com/19266024/47245523-a41b3800-d3c7-11e8-8a93-19d7f8cfc821.png)

**Comment by raviram203** [comment]
Worked. Thanks.
